export const projects = [
    {
        name: "Fitness Tracker",
        slug: "fitness-tracker",
        description: "Track your workouts, calories, and progress with detailed statistics and personalized insights. Built with React Native and Firebase for real-time data synchronization.",
        technologies: ["React Native", "Firebase (Firestore, Auth)", "Expo", "React Navigation"],
        image: "/images/fitness-tracker.png",
        url: "/apps/fitness-tracker",
    },
    {
        name: "Task Manager",
        slug: "task-manager",
        description: "Organize your daily tasks, set reminders, and manage your to-do lists efficiently. Features offline support with local data storage.",
        technologies: ["React Native", "SQLite", "React Navigation", "Expo"],
        image: "/images/task-manager.png",
        url: "/apps/task-manager",
    },
    {
        name: "Social Media App",
        slug: "social-media-app",
        description: "A mobile social media platform for sharing photos, videos, and connecting with friends. Includes user profiles, feeds, and real-time chat.",
        technologies: ["React Native", "Firebase (Firestore, Storage, Auth)", "Expo", "React Navigation", "Redux"],
        image: "/images/social-media-app.png",
        url: "/apps/social-media-app",
    },
    {
        name: "E-commerce Mobile Store",
        slug: "ecommerce-mobile-store",
        description: "Browse products, add to cart, and complete secure purchases on a user-friendly mobile e-commerce platform.",
        technologies: ["React Native", "Firebase (Firestore, Auth)", "Stripe (for payments)", "Expo", "React Navigation"],
        image: "/images/ecommerce-mobile-store.png",
        url: "/apps/ecommerce-mobile-store",
    },
    {
        name: "Chat Application",
        slug: "chat-application",
        description: "A real-time messaging application with private and group chats, push notifications, and media sharing.",
        technologies: ["React Native", "Firebase (Firestore, Cloud Messaging)", "Expo", "Gifted Chat (UI Library)"],
        image: "/images/chat-application.png",
        url: "/apps/chat-application",
    },
    {
        name: "Expense Tracker",
        slug: "expense-tracker",
        description: "Track and categorize your expenses, set budgets, and visualize spending habits with interactive charts.",
        technologies: ["React Native", "SQLite", "React Navigation", "Victory Native (Charting Library)", "Expo"],
        image: "/images/expense-tracker.png",
        url: "/apps/expense-tracker",
    },
    {
        name: "Recipe Finder",
        slug: "recipe-finder",
        description: "Discover and save recipes, create shopping lists, and filter by ingredients or dietary restrictions. Integrates with a recipe API.",
        technologies: ["React Native", "Expo", "Edamam API", "React Navigation"],
        image: "/images/recipe-finder.png",
        url: "/apps/recipe-finder",
    },
    {
        name: "Weather App",
        slug: "weather-app",
        description: "Get real-time weather forecasts and conditions for any location with a clean and intuitive interface.",
        technologies: ["React Native", "OpenWeatherMap API", "Expo Location", "React Navigation"],
        image: "/images/weather-app.png",
        url: "/apps/weather-app",
    },
];

